[package]
name = "RustFileEncryption"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.5.3"
aes-gcm = "0.9.4"
rand = "0.8.5"
argon2 = "0.4"